# Generated by Django 4.2.3 on 2023-07-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("writer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="title",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="title",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="editorial",
            name="title",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="home",
            name="title",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="interview",
            name="title",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="prose",
            name="title",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="title",
            field=models.TextField(null=True),
        ),
    ]
