# Generated by Django 4.2.3 on 2023-07-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "writer",
            "0002_about_title_contact_title_editorial_title_home_title_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("pdf_file", models.FileField(upload_to="about_pdfs/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
